[tools]
go = "1.22"
"go:github.com/spf13/cobra-cli" = "latest"
"go:github.com/vektra/mockery/v2" = "v2.42"
"go:gotest.tools/gotestsum" = "latest"

[tasks.build]
description = "Build the CLI binary"
run = "go build"
alias = "b"
sources = ["cmd/**/*.go"]

[tasks.test]
description = "Run tests"
run = "gotestsum ./test/..."
sources = ["test/**/*.go"]
